const PartnerInfo = require('../db').PartnerInfo
const BankInfo = require('../db').BankInfo
const TaxInfo = require('../db').TaxInfo
const Website = require('../db').Website
const App = require('../db').App

function createPartner(){
    PartnerInfo.bulkCreate([
        {
            userId:1,
            company:'lkndsf',
            storeName:'sefwf',
            partnerId:'iheif',
            info:'sdfknsk',
            appCategory:'sdfs',
            partnerCategory:'fsdf',
            trafficCategory:'213',
            income:'2131',
            uniqueVisitor:'123',
            reason:'werw',
            source:'dwf',
            state:'erwdf',
        },
        {
            userId:2,
            company:'lkndsf',
            storeName:'sefwf',
            partnerId:'dfsvd',
            info:'sdfknsk',
            appCategory:'sdfs',
            partnerCategory:'fsdf',
            trafficCategory:'213',
            income:'2131',
            uniqueVisitor:'123',
            reason:'werw',
            source:'dwf',
            state:'erwdf',
        },
        {
            userId:3,
            company:'lkndsf',
            storeName:'sefwf',
            partnerId:'qertwrg',
            info:'sdfknsk',
            appCategory:'sdfs',
            partnerCategory:'fsdf',
            trafficCategory:'213',
            income:'2131',
            uniqueVisitor:'123',
            reason:'werw',
            source:'dwf',
            state:'erwdf',
        },
    ])
    .then(()=>{
        TaxInfo.bulkCreate([
            {
                partnerInfoId:1,
                GST:'2341',
                PAN:'23423'
            },
            {
                partnerInfoId:2,
                GST:'12312',
                PAN:'2342'
            },
            {
                partnerInfoId:3,
                GST:'468467',
                PAN:'53636'
            },
        ])
        BankInfo.bulkCreate([
            {
                partnerInfoId:1,
                name:'123ffq',
                type:'werqer',
                number:'234234',
                IFSC:'31124',    
            },
            {
                partnerInfoId:2,
                name:'123ffq',
                type:'werqer',
                number:'234234',
                IFSC:'31124',    
            },
            {
                partnerInfoId:3,
                name:'123ffq',
                type:'werqer',
                number:'234234',
                IFSC:'31124',    
            },
        ])
        Website.bulkCreate([
            {
                partnerInfoId:1,
                value:'234134dfsf'                   
            },
            {
                partnerInfoId:1,
                value:'wrgw'                   
            },
            {
                partnerInfoId:1,
                value:'32r23r'                   
            },
        ])
        App.bulkCreate([
            {
                partnerInfoId:1,
                value:'234134dfsf'                   
            },
            {
                partnerInfoId:1,
                value:'234wrgwg134dfsf'                   
            },
            {
                partnerInfoId:1,
                value:'2341wer34dfsf'                   
            },
        ])
    })
}

exports = module.exports = {
    createPartner
}